package initializer

// DocunyanYAMLTemplate contains the default YAML configuration template
const DocunyanYAMLTemplate = `info:
  title: Example API
  version: 1.0.0
  description: API documentation generated by Docunyan

servers:
  - url: http://localhost:8080/api
    description: Development server

authorization:
  name: X-API-KEY
  type: [apiKey]
  scheme: [apiKey]
  in: header

paths:
  /users:
    get:
      summary: Get all users
      tags:
        - Users
      authorization: true
      query:
        page: int
        limit: int
      responses:
        200:
          description: List of users
          schema: UserListResponse
        401:
          description: Unauthorized
          schema: ErrorResponse

  /users/{id}:
    get:
      summary: Get user by ID
      tags:
        - Users
      authorization: true
      responses:
        200:
          description: User details
          schema: UserResponse
        404:
          description: User not found
          schema: ErrorResponse

    put:
      summary: Update user
      tags:
        - Users
      authorization: true
      requestBody: UpdateUserRequest
      responses:
        200:
          description: User updated successfully
          schema: UserResponse
        400:
          description: Invalid request
          schema: ErrorResponse

  /users:
    post:
      summary: Create new user
      tags:
        - Users
      authorization: false
      requestBody: CreateUserRequest
      responses:
        201:
          description: User created successfully
          schema: UserResponse
        400:
          description: Invalid request
          schema: ErrorResponse
`

// ExampleDTOTemplate contains the default Go DTO template
const ExampleDTOTemplate = `package dto

import "time"

// User represents a user in the system
type User struct {
	ID        int64     ` + "`json:\"id\"`" + `
	Username  string    ` + "`json:\"username\" validate:\"required\"`" + `
	Email     string    ` + "`json:\"email\" validate:\"required\"`" + `
	FullName  string    ` + "`json:\"full_name\"`" + `
	CreatedAt time.Time ` + "`json:\"created_at\"`" + `
	UpdatedAt time.Time ` + "`json:\"updated_at\"`" + `
}

// CreateUserRequest represents the request body for creating a user
type CreateUserRequest struct {
	Username string ` + "`json:\"username\" validate:\"required\"`" + `
	Email    string ` + "`json:\"email\" validate:\"required\"`" + `
	Password string ` + "`json:\"password\" validate:\"required\"`" + `
	FullName string ` + "`json:\"full_name,omitempty\"`" + `
}

// UpdateUserRequest represents the request body for updating a user
type UpdateUserRequest struct {
	Username string ` + "`json:\"username,omitempty\"`" + `
	Email    string ` + "`json:\"email,omitempty\"`" + `
	FullName string ` + "`json:\"full_name,omitempty\"`" + `
}

// UserResponse represents a single user response
type UserResponse struct {
	Success bool   ` + "`json:\"success\"`" + `
	Message string ` + "`json:\"message\"`" + `
	Data    User   ` + "`json:\"data\"`" + `
}

// UserListResponse represents a list of users response
type UserListResponse struct {
	Success bool   ` + "`json:\"success\"`" + `
	Message string ` + "`json:\"message\"`" + `
	Data    []User ` + "`json:\"data\"`" + `
	Meta    Meta   ` + "`json:\"meta\"`" + `
}

// Meta represents pagination metadata
type Meta struct {
	Page       int ` + "`json:\"page\"`" + `
	Limit      int ` + "`json:\"limit\"`" + `
	TotalItems int ` + "`json:\"total_items\"`" + `
	TotalPages int ` + "`json:\"total_pages\"`" + `
}

// ErrorResponse represents an error response
type ErrorResponse struct {
	Success bool   ` + "`json:\"success\"`" + `
	Message string ` + "`json:\"message\"`" + `
	Error   string ` + "`json:\"error,omitempty\"`" + `
}
`
